name = "Coder Lightweight"
license = "MIT"
licenselink = "https://github.com/PandaSekh/hugo-coder-lt/blob/master/LICENSE.md"
description = "A lightweight, simple and clean blog theme for Hugo"
homepage = "https://github.com/PandaSekh/hugo-coder-lt"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "favicon",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.79.0"

[author]
name = "Alessio Franceschi"
homepage = "https://alessiofranceschi.dev"
[original]
name = "Luiz F. A. de Prá"
homepage = "https://luizdepra.com"
repo = "https://github.com/luizdepra/hugo-coder"